export const DELETE_GOODS_DONE = 'DELETE_GOODS_DONE';
export const DELETE_GOODS_FAIL = 'DELETE_GOODS_FAIL';
export const FILTER_GOODS_DONE = 'FILTER_GOODS_DONE';
export const FILTER_GOODS_FAIL = 'FILTER_GOODS_FAIL';